In [2]:
module_meanings = {
    "ii_portad": "cover_book",
    "ii_su": "land_household",
    "ii_su1": "land_household_details",
    "ii_inr": "rural_income",
    "ii_nna": "non_agricultural_business",
    "ii_nna1": "non_agricultural_business_details",
    "ii_ah": "household_assets",
    "ii_crh": "household_credit",
    "ii_in": "household_non_labor_income",
    "ii_se": "household_economic_shocks",
    "ii_vlh": "household_crime_victimization",
    "ii_vlh1": "household_crime_victimization_details",
    "ii_ne": "interview_session_notes",
    "ii_conpor": "visits_control",
}

In [3]:
from pathlib import Path


import sys 

### show the first path in sys.path
print(sys.path[0])
## show project root 
print(Path.cwd())

DATA_DIR = Path.cwd() / "data" / "hh09dta_b2"
JSON_DIR = DATA_DIR / "codebook_json"

/Library/Frameworks/Python.framework/Versions/3.13/lib/python313.zip
/Users/cyprienfourcroy/Desktop/CoReLaTTe

In [4]:
import os 
for file in os.listdir(DATA_DIR):
    print(file)

ii_ne.dta
.DS_Store
code_book.pdf
ii_ah.dta
ii_nna1.dta
ii_conpor.dta
ii_su1.dta
ii_crh.dta
codebook_json
ii_su.dta
ii_portad.dta
ii_in.dta
ii_se.dta
ii_nna.dta
ii_vlh1.dta
ii_vlh.dta
ii_inr.dta

In [5]:
import pandas as pd


df_ii_portad_cover_book = pd.read_stata(DATA_DIR / "ii_portad.dta")
df_ii_su_land_household = pd.read_stata(DATA_DIR / "ii_su.dta")
df_ii_su1_land_household_details = pd.read_stata(DATA_DIR / "ii_su1.dta")
df_ii_inr_rural_income = pd.read_stata(DATA_DIR / "ii_inr.dta")
df_ii_nna_non_agricultural_business = pd.read_stata(DATA_DIR / "ii_nna.dta")
df_ii_nna1_non_agricultural_business_details = pd.read_stata(DATA_DIR / "ii_nna1.dta")
df_ii_ah_household_assets = pd.read_stata(DATA_DIR / "ii_ah.dta")
df_ii_crh_household_credit = pd.read_stata(DATA_DIR / "ii_crh.dta")
df_ii_in_household_non_labor_income = pd.read_stata(DATA_DIR / "ii_in.dta")
df_ii_se_household_economic_shocks = pd.read_stata(DATA_DIR / "ii_se.dta")
df_ii_vlh_household_crime_victimization = pd.read_stata(DATA_DIR / "ii_vlh.dta")
df_ii_vlh1_household_crime_victimization_details = pd.read_stata(DATA_DIR / "ii_vlh1.dta")
df_ii_ne_interview_session_notes = pd.read_stata(DATA_DIR / "ii_ne.dta")
df_ii_conpor_visits_control = pd.read_stata(DATA_DIR / "ii_conpor.dta")

In [8]:
df_ii_vlh_household_crime_victimization

,folio,vlh01a,vlh01b,vlh01c,vlh01d,vlh01e,vlh01f,vlh01g,vlh01h,vlh01i,...,vlh14,vlh14a,vlh15,vlh15a,vlh16,vlh16a,vlh17,vlh17a,vlh18,vlh18a
0,000010AP00,3.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,...,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,0.0
1,000010BP03,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,3.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0
2,000020AP00,3.0,1.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0
3,000020CP03,3.0,1.0,1.0,3.0,3.0,1.0,3.0,3.0,3.0,...,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0,NaN
4,000030AP00,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,9.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9087,107530AP00,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0
9088,107540AP00,1.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,0.0
9089,107570AP00,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0
9090,107580AP00,3.0,1.0,1.0,3.0,3.0,3.0,3.0,1.0,3.0,...,NaN,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0
9091,107590AP00,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,0.0

In [5]:

natural_sampling_dict = {

    1: "ii_portad",

    2: {
        "non_detailed": "ii_su",
        "detailed": "ii_su1",
    },

    3: "ii_inr",

    4: {
        "non_detailed": "ii_nna",
        "detailed": "ii_nna1",
    },

    5: "ii_ah",
    6: "ii_crh",
    7: "ii_in",
    8: "ii_se",

    9: {
        "non_detailed": "ii_vlh",
        "detailed": "ii_vlh1",
    },

    10: "ii_ne",
    11: "ii_conpor",
}

In [6]:
import random

list_of_subsets = []

for _ in range(10):

    subset = [1]

    pair = random.sample(range(2, 10), 2)

    subset.extend(pair)

    subset_list = []

    for table_number in subset:

        value = natural_sampling_dict[table_number]

        if isinstance(value, dict):
            subset_list.append(value["non_detailed"])
        else:
            subset_list.append(value)

    list_of_subsets.append(subset_list)

for element in list_of_subsets:
    print(element)

['ii_portad', 'ii_su', 'ii_ah']
['ii_portad', 'ii_inr', 'ii_crh']
['ii_portad', 'ii_ah', 'ii_vlh']
['ii_portad', 'ii_in', 'ii_ah']
['ii_portad', 'ii_inr', 'ii_ah']
['ii_portad', 'ii_nna', 'ii_se']
['ii_portad', 'ii_in', 'ii_ah']
['ii_portad', 'ii_inr', 'ii_se']
['ii_portad', 'ii_se', 'ii_in']
['ii_portad', 'ii_nna', 'ii_su']

In [7]:
from pathlib import Path
import sys



QUERY_GENERATION_DIR = Path.cwd() / "src" / "model" / "Corelatte" / "QueryGeneration"

sys.path.append(str(QUERY_GENERATION_DIR))

In [8]:
from SQL_TYPE_ALONE import compile_query_plan, validate_query_plan, QueryPlan, build_query_plan_prompt

In [9]:
### prepare dataframes: dict[str, pd.DataFrame], dataframe_description: str

count = 0
for element in list_of_subsets:
    if count > 0:
        break

    for table_name in element:
        df = pd.read_stata(DATA_DIR / f"{table_name}.dta")
        json_path = JSON_DIR / f"{table_name}_enriched.json"
        ### load the json as dict 
        json_dict = pd.read_json(json_path, orient="index").to_dict()

        print(json_dict)


        print(df.columns)
    count += 1

{'meaning': {'edad': 'Age Interviewed', 'ent': 'State', 'folio': 'Household ID', 'ls': 'Individual ID', 'rel': 'Result Interview'}, 'values_label': {'edad': nan, 'ent': {'Baja California': '2', 'Baja California Sur': '3', 'Campeche': '4', 'Coahuila': '5', 'Colima': '6', 'Chiapas': '7', 'Distrito Federal': '9', 'Durango': '10', 'Guanajuato': '11', 'Guerrero': '12', 'Hidalgo': '13', 'Jalisco': '14', 'Estado de México': '15', 'Michoacán': '16', 'Morelos': '17', 'Nayarit': '18', 'Nuevo León': '19', 'Oaxaca': '20', 'Puebla': '21', 'Querétaro': '22', 'Sinaloa': '25', 'Sonora': '26', 'Tamaulipas': '28', 'Tlaxcala': '29', 'Veracruz': '30', 'Yucatán': '31', 'Zacatecas': '32'}, 'folio': nan, 'ls': nan, 'rel': nan}}
Index(['edad', 'ent', 'folio', 'ls', 'rel'], dtype='object')
{'meaning': {'folio': 'Household ID', 'su01': 'HHM use a plot/land for showing/farming/vegetable', 'su03': '# Total plots/pieces of land', 'su021': 'Parcels/Owned Land', 'su022': "# Parcels/someone else's land", 'su22a_1': 'Weight/measure unit a roll', 'su22a_2': 'Weight/measure a Roll', 'su22b_1': 'Weight/measure unit gross', 'su22b_2': 'Weight/measure gross', 'su22c_1': 'Unit sack', 'su22c_2': 'Other weight/measure sack', 'su22d_1': 'Other Weight/measure unit', 'su22d_21': 'Other weight/measure', 'su22e_1': 'Weight/measure other unit', 'su22e_21': 'Other weight/measure', 'su231': 'Expense in chemical fertilizer', 'su232': 'Expense in manure', 'su233': 'Expense in pesticides', 'su234': 'Expense in seeds', 'su235': 'Expense in tractor rental', 'su236': 'Expense in yoke', 'su237': 'Expense in workers', 'su238': 'Expense in water', 'su239': 'Expense in fuel', 'su2310': "Doesn't apply/specify/remember", 'su2311_1': 'Other expense specify'}, 'values_label': {'folio': nan, 'su01': {'Yes': '1', 'No': '3'}, 'su03': nan, 'su021': {'Yes': '1', 'No': '3'}, 'su022': nan, 'su22a_1': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}, 'su22a_2': nan, 'su22b_1': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}, 'su22b_2': nan, 'su22c_1': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}, 'su22c_2': nan, 'su22d_1': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}, 'su22d_21': nan, 'su22e_1': {'Kg': '1', 'Ton': '2', 'Cubic meters': '3', 'DK': '8'}, 'su22e_21': nan, 'su231': nan, 'su232': nan, 'su233': nan, 'su234': nan, 'su235': nan, 'su236': nan, 'su237': nan, 'su238': nan, 'su239': nan, 'su2310': nan, 'su2311_1': nan}}
Index(['folio', 'su01', 'su03', 'su021', 'su022', 'su22a_1', 'su22a_2',
       'su22b_1', 'su22b_2', 'su22c_1', 'su22c_2', 'su22d_1', 'su22d_21',
       'su22e_1', 'su22e_21', 'su231', 'su232', 'su233', 'su234', 'su235',
       'su236', 'su237', 'su238', 'su239', 'su2310', 'su2311_1'],
      dtype='object')
{'meaning': {'folio': 'Household ID', 'ls': 'Individual ID', 'ah03a': 'HHM owns living house?', 'ah03b': 'HHM owns other house/building?', 'ah03c': 'HHM owns bicycles?', 'ah03d': 'HHM owns motor vehicle?', 'ah03d1': 'HHM owns motor car?', 'ah03e': 'HHM owns electronic device?', 'ah03f': 'HHM owns wash machine/stove?', 'ah03g': 'HHM owns domestic appliance?', 'ah03h': 'HHM owns financial assets/afores?', 'ah03i': 'HHM owns machinary/tractor?', 'ah03j': 'HHM owns bull/cow?', 'ah03k': 'HHM owns horses/mules?', 'ah03l': 'HHM owns pigs/goats?', 'ah03m': 'HHM owns poultry?', 'ah03n': 'HHM owns other assets?', 'ah04a_1': 'Value living house?', 'ah04a_2': 'Value living house', 'ah04b_1': 'Value other house?', 'ah04b_2': 'Value other house', 'ah04c_1': 'Value bicycles?', 'ah04c_2': 'Value bicycles', 'ah04d_1': 'Value motor vehicle?', 'ah04d_2': 'Value motor vehicle', 'ah04d1_1': 'Value motor car?', 'ah04d1_2': 'Value motor car', 'ah04e_1': 'Value electronic device?', 'ah04e_2': 'Value electronic device', 'ah04f_1': 'Value wash machine/stove?', 'ah04f_2': 'Value wash machine/stove', 'ah04g_1': 'Value domestic appliance?', 'ah04g_2': 'Value domestic appliance', 'ah04h_1': 'Value financial assets/afores?', 'ah04h_2': 'Value financial assets/afores', 'ah04i_1': 'Value machinary/tractor?', 'ah04i_2': 'Value machinary/tractor', 'ah04j_1': 'Value bull/cow?', 'ah04j_2': 'Value bull/cow', 'ah04k_1': 'Value horses/mules?', 'ah04k_2': 'Value horses/mules', 'ah04l_1': 'Value pigs/goats?', 'ah04l_2': 'Value pigs/goats', 'ah04m_1': 'Value poultry?', 'ah04m_2': 'Value poultry', 'ah04n_1': 'Value other assets?', 'ah04n_2': 'Value other assets'}, 'values_label': {'folio': nan, 'ls': nan, 'ah03a': {'Yes': '1', 'No': '3'}, 'ah03b': {'Yes': '1', 'No': '3'}, 'ah03c': {'Yes': '1', 'No': '3'}, 'ah03d': {'Yes': '1', 'No': '3'}, 'ah03d1': {'Yes': '1', 'No': '3'}, 'ah03e': {'Yes': '1', 'No': '3'}, 'ah03f': {'Yes': '1', 'No': '3'}, 'ah03g': {'Yes': '1', 'No': '3'}, 'ah03h': {'Yes': '1', 'No': '3'}, 'ah03i': {'Yes': '1', 'No': '3'}, 'ah03j': {'Yes': '1', 'No': '3'}, 'ah03k': {'Yes': '1', 'No': '3'}, 'ah03l': {'Yes': '1', 'No': '3'}, 'ah03m': {'Yes': '1', 'No': '3'}, 'ah03n': {'Yes': '1', 'No': '3'}, 'ah04a_1': {'Yes': '1', 'DK': '8'}, 'ah04a_2': nan, 'ah04b_1': {'Yes': '1', 'DK': '8'}, 'ah04b_2': nan, 'ah04c_1': {'Yes': '1', 'DK': '8'}, 'ah04c_2': nan, 'ah04d_1': {'Yes': '1', 'DK': '8'}, 'ah04d_2': nan, 'ah04d1_1': nan, 'ah04d1_2': nan, 'ah04e_1': {'Yes': '1', 'DK': '8'}, 'ah04e_2': nan, 'ah04f_1': {'Yes': '1', 'DK': '8'}, 'ah04f_2': nan, 'ah04g_1': {'Yes': '1', 'DK': '8'}, 'ah04g_2': nan, 'ah04h_1': {'Yes': '1', 'DK': '8'}, 'ah04h_2': nan, 'ah04i_1': {'Yes': '1', 'DK': '8'}, 'ah04i_2': nan, 'ah04j_1': {'Yes': '1', 'DK': '8'}, 'ah04j_2': nan, 'ah04k_1': {'Yes': '1', 'DK': '8'}, 'ah04k_2': nan, 'ah04l_1': {'Yes': '1', 'DK': '8'}, 'ah04l_2': nan, 'ah04m_1': {'Yes': '1', 'DK': '8'}, 'ah04m_2': nan, 'ah04n_1': {'Yes': '1', 'DK': '8'}, 'ah04n_2': nan}}
Index(['ah03a', 'ah03b', 'ah03c', 'ah03d', 'ah03d1', 'ah03e', 'ah03f', 'ah03g',
       'ah03h', 'ah03i', 'ah03j', 'ah03k', 'ah03l', 'ah03m', 'ah03n',
       'ah04a_1', 'ah04a_2', 'ah04b_1', 'ah04b_2', 'ah04c_1', 'ah04c_2',
       'ah04d1_1', 'ah04d1_2', 'ah04d_1', 'ah04d_2', 'ah04e_1', 'ah04e_2',
       'ah04f_1', 'ah04f_2', 'ah04g_1', 'ah04g_2', 'ah04h_1', 'ah04h_2',
       'ah04i_1', 'ah04i_2', 'ah04j_1', 'ah04j_2', 'ah04k_1', 'ah04k_2',
       'ah04l_1', 'ah04l_2', 'ah04m_1', 'ah04m_2', 'ah04n_1', 'ah04n_2',
       'ah05a', 'ah05b', 'ah05g', 'ah05h', 'ah05i', 'ah05n', 'ah06a_1',
       'ah06a_2', 'ah06b_1', 'ah06b_2', 'ah06g_1', 'ah06g_2', 'ah06h_1',
       'ah06h_2', 'ah06i_1', 'ah06i_2', 'ah06n_1', 'ah06n_2', 'folio', 'ls'],
      dtype='object')

In [10]:
import json

def variable_metadata_to_text(json_dict: dict) -> str:
    lines = []
    print("title json dict :", json_dict)

    for column_name, metadata in json_dict.items():
       
        meaning = metadata.get("meaning", "No meaning provided")
        if meaning == "No meaning provided":
            print(f"Warning: No meaning provided for column '{column_name}'.")
        values_label = metadata.get("values_label")

        lines.append(f'Column "{column_name}" means: {meaning}.')

        if values_label:
            lines.append("Possible values:")
            for label, value in values_label.items():
                lines.append(f"  - {value}: {label}")

        lines.append("")  # blank line between variables

    return "\n".join(lines)

In [11]:
import json
import pandas as pd

count = 0

for element in list_of_subsets:
    if count > 0:
        break

    for table_name in element:
        print(f"\nProcessing table: {table_name}")
        df = pd.read_stata(DATA_DIR / f"{table_name}.dta")

        json_path = JSON_DIR / f"{table_name}_enriched.json"

        with open(json_path, "r", encoding="utf-8") as f:
            json_dict = json.load(f)

        text_description = variable_metadata_to_text(json_dict)

        print(f"\n===== {table_name} =====\n")
        print(text_description)

        print(df.columns)

    count += 1

Processing table: ii_portad
title json dict : {'edad': {'meaning': 'Age Interviewed'}, 'ent': {'meaning': 'State', 'values_label': {'Baja California': '2', 'Baja California Sur': '3', 'Campeche': '4', 'Coahuila': '5', 'Colima': '6', 'Chiapas': '7', 'Distrito Federal': '9', 'Durango': '10', 'Guanajuato': '11', 'Guerrero': '12', 'Hidalgo': '13', 'Jalisco': '14', 'Estado de México': '15', 'Michoacán': '16', 'Morelos': '17', 'Nayarit': '18', 'Nuevo León': '19', 'Oaxaca': '20', 'Puebla': '21', 'Querétaro': '22', 'Sinaloa': '25', 'Sonora': '26', 'Tamaulipas': '28', 'Tlaxcala': '29', 'Veracruz': '30', 'Yucatán': '31', 'Zacatecas': '32'}}, 'folio': {'meaning': 'Household ID'}, 'ls': {'meaning': 'Individual ID'}, 'rel': {'meaning': 'Result Interview'}}

===== ii_portad =====

Column "edad" means: Age Interviewed.

Column "ent" means: State.
Possible values:
  - 2: Baja California
  - 3: Baja California Sur
  - 4: Campeche
  - 5: Coahuila
  - 6: Colima
  - 7: Chiapas
  - 9: Distrito Federal
  - 10: Durango
  - 11: Guanajuato
  - 12: Guerrero
  - 13: Hidalgo
  - 14: Jalisco
  - 15: Estado de México
  - 16: Michoacán
  - 17: Morelos
  - 18: Nayarit
  - 19: Nuevo León
  - 20: Oaxaca
  - 21: Puebla
  - 22: Querétaro
  - 25: Sinaloa
  - 26: Sonora
  - 28: Tamaulipas
  - 29: Tlaxcala
  - 30: Veracruz
  - 31: Yucatán
  - 32: Zacatecas

Column "folio" means: Household ID.

Column "ls" means: Individual ID.

Column "rel" means: Result Interview.

Index(['edad', 'ent', 'folio', 'ls', 'rel'], dtype='object')

Processing table: ii_su
title json dict : {'folio': {'meaning': 'Household ID'}, 'su01': {'meaning': 'HHM use a plot/land for showing/farming/vegetable', 'values_label': {'Yes': '1', 'No': '3'}}, 'su03': {'meaning': '# Total plots/pieces of land'}, 'su021': {'meaning': 'Parcels/Owned Land', 'values_label': {'Yes': '1', 'No': '3'}}, 'su022': {'meaning': "# Parcels/someone else's land"}, 'su22a_1': {'meaning': 'Weight/measure unit a roll', 'values_label': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}}, 'su22a_2': {'meaning': 'Weight/measure a Roll'}, 'su22b_1': {'meaning': 'Weight/measure unit gross', 'values_label': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}}, 'su22b_2': {'meaning': 'Weight/measure gross'}, 'su22c_1': {'meaning': 'Unit sack', 'values_label': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}}, 'su22c_2': {'meaning': 'Other weight/measure sack'}, 'su22d_1': {'meaning': 'Other Weight/measure unit', 'values_label': {'Kg.': '1', 'Ton.': '2', 'Cubic meters': '3', 'DK': '8'}}, 'su22d_21': {'meaning': 'Other weight/measure'}, 'su22e_1': {'meaning': 'Weight/measure other unit', 'values_label': {'Kg': '1', 'Ton': '2', 'Cubic meters': '3', 'DK': '8'}}, 'su22e_21': {'meaning': 'Other weight/measure'}, 'su231': {'meaning': 'Expense in chemical fertilizer'}, 'su232': {'meaning': 'Expense in manure'}, 'su233': {'meaning': 'Expense in pesticides'}, 'su234': {'meaning': 'Expense in seeds'}, 'su235': {'meaning': 'Expense in tractor rental'}, 'su236': {'meaning': 'Expense in yoke'}, 'su237': {'meaning': 'Expense in workers'}, 'su238': {'meaning': 'Expense in water'}, 'su239': {'meaning': 'Expense in fuel'}, 'su2310': {'meaning': "Doesn't apply/specify/remember"}, 'su2311_1': {'meaning': 'Other expense specify'}}

===== ii_su =====

Column "folio" means: Household ID.

Column "su01" means: HHM use a plot/land for showing/farming/vegetable.
Possible values:
  - 1: Yes
  - 3: No

Column "su03" means: # Total plots/pieces of land.

Column "su021" means: Parcels/Owned Land.
Possible values:
  - 1: Yes
  - 3: No

Column "su022" means: # Parcels/someone else's land.

Column "su22a_1" means: Weight/measure unit a roll.
Possible values:
  - 1: Kg.
  - 2: Ton.
  - 3: Cubic meters
  - 8: DK

Column "su22a_2" means: Weight/measure a Roll.

Column "su22b_1" means: Weight/measure unit gross.
Possible values:
  - 1: Kg.
  - 2: Ton.
  - 3: Cubic meters
  - 8: DK

Column "su22b_2" means: Weight/measure gross.

Column "su22c_1" means: Unit sack.
Possible values:
  - 1: Kg.
  - 2: Ton.
  - 3: Cubic meters
  - 8: DK

Column "su22c_2" means: Other weight/measure sack.

Column "su22d_1" means: Other Weight/measure unit.
Possible values:
  - 1: Kg.
  - 2: Ton.
  - 3: Cubic meters
  - 8: DK

Column "su22d_21" means: Other weight/measure.

Column "su22e_1" means: Weight/measure other unit.
Possible values:
  - 1: Kg
  - 2: Ton
  - 3: Cubic meters
  - 8: DK

Column "su22e_21" means: Other weight/measure.

Column "su231" means: Expense in chemical fertilizer.

Column "su232" means: Expense in manure.

Column "su233" means: Expense in pesticides.

Column "su234" means: Expense in seeds.

Column "su235" means: Expense in tractor rental.

Column "su236" means: Expense in yoke.

Column "su237" means: Expense in workers.

Column "su238" means: Expense in water.

Column "su239" means: Expense in fuel.

Column "su2310" means: Doesn't apply/specify/remember.

Column "su2311_1" means: Other expense specify.

Index(['folio', 'su01', 'su03', 'su021', 'su022', 'su22a_1', 'su22a_2',
       'su22b_1', 'su22b_2', 'su22c_1', 'su22c_2', 'su22d_1', 'su22d_21',
       'su22e_1', 'su22e_21', 'su231', 'su232', 'su233', 'su234', 'su235',
       'su236', 'su237', 'su238', 'su239', 'su2310', 'su2311_1'],
      dtype='object')

Processing table: ii_ah
title json dict : {'folio': {'meaning': 'Household ID'}, 'ls': {'meaning': 'Individual ID'}, 'ah03a': {'meaning': 'HHM owns living house?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03b': {'meaning': 'HHM owns other house/building?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03c': {'meaning': 'HHM owns bicycles?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03d': {'meaning': 'HHM owns motor vehicle?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03d1': {'meaning': 'HHM owns motor car?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03e': {'meaning': 'HHM owns electronic device?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03f': {'meaning': 'HHM owns wash machine/stove?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03g': {'meaning': 'HHM owns domestic appliance?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03h': {'meaning': 'HHM owns financial assets/afores?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03i': {'meaning': 'HHM owns machinary/tractor?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03j': {'meaning': 'HHM owns bull/cow?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03k': {'meaning': 'HHM owns horses/mules?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03l': {'meaning': 'HHM owns pigs/goats?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03m': {'meaning': 'HHM owns poultry?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah03n': {'meaning': 'HHM owns other assets?', 'values_label': {'Yes': '1', 'No': '3'}}, 'ah04a_1': {'meaning': 'Value living house?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04a_2': {'meaning': 'Value living house'}, 'ah04b_1': {'meaning': 'Value other house?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04b_2': {'meaning': 'Value other house'}, 'ah04c_1': {'meaning': 'Value bicycles?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04c_2': {'meaning': 'Value bicycles'}, 'ah04d_1': {'meaning': 'Value motor vehicle?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04d_2': {'meaning': 'Value motor vehicle'}, 'ah04d1_1': {'meaning': 'Value motor car?'}, 'ah04d1_2': {'meaning': 'Value motor car'}, 'ah04e_1': {'meaning': 'Value electronic device?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04e_2': {'meaning': 'Value electronic device'}, 'ah04f_1': {'meaning': 'Value wash machine/stove?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04f_2': {'meaning': 'Value wash machine/stove'}, 'ah04g_1': {'meaning': 'Value domestic appliance?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04g_2': {'meaning': 'Value domestic appliance'}, 'ah04h_1': {'meaning': 'Value financial assets/afores?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04h_2': {'meaning': 'Value financial assets/afores'}, 'ah04i_1': {'meaning': 'Value machinary/tractor?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04i_2': {'meaning': 'Value machinary/tractor'}, 'ah04j_1': {'meaning': 'Value bull/cow?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04j_2': {'meaning': 'Value bull/cow'}, 'ah04k_1': {'meaning': 'Value horses/mules?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04k_2': {'meaning': 'Value horses/mules'}, 'ah04l_1': {'meaning': 'Value pigs/goats?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04l_2': {'meaning': 'Value pigs/goats'}, 'ah04m_1': {'meaning': 'Value poultry?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04m_2': {'meaning': 'Value poultry'}, 'ah04n_1': {'meaning': 'Value other assets?', 'values_label': {'Yes': '1', 'DK': '8'}}, 'ah04n_2': {'meaning': 'Value other assets'}}

===== ii_ah =====

Column "folio" means: Household ID.

Column "ls" means: Individual ID.

Column "ah03a" means: HHM owns living house?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03b" means: HHM owns other house/building?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03c" means: HHM owns bicycles?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03d" means: HHM owns motor vehicle?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03d1" means: HHM owns motor car?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03e" means: HHM owns electronic device?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03f" means: HHM owns wash machine/stove?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03g" means: HHM owns domestic appliance?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03h" means: HHM owns financial assets/afores?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03i" means: HHM owns machinary/tractor?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03j" means: HHM owns bull/cow?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03k" means: HHM owns horses/mules?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03l" means: HHM owns pigs/goats?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03m" means: HHM owns poultry?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah03n" means: HHM owns other assets?.
Possible values:
  - 1: Yes
  - 3: No

Column "ah04a_1" means: Value living house?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04a_2" means: Value living house.

Column "ah04b_1" means: Value other house?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04b_2" means: Value other house.

Column "ah04c_1" means: Value bicycles?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04c_2" means: Value bicycles.

Column "ah04d_1" means: Value motor vehicle?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04d_2" means: Value motor vehicle.

Column "ah04d1_1" means: Value motor car?.

Column "ah04d1_2" means: Value motor car.

Column "ah04e_1" means: Value electronic device?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04e_2" means: Value electronic device.

Column "ah04f_1" means: Value wash machine/stove?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04f_2" means: Value wash machine/stove.

Column "ah04g_1" means: Value domestic appliance?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04g_2" means: Value domestic appliance.

Column "ah04h_1" means: Value financial assets/afores?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04h_2" means: Value financial assets/afores.

Column "ah04i_1" means: Value machinary/tractor?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04i_2" means: Value machinary/tractor.

Column "ah04j_1" means: Value bull/cow?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04j_2" means: Value bull/cow.

Column "ah04k_1" means: Value horses/mules?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04k_2" means: Value horses/mules.

Column "ah04l_1" means: Value pigs/goats?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04l_2" means: Value pigs/goats.

Column "ah04m_1" means: Value poultry?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04m_2" means: Value poultry.

Column "ah04n_1" means: Value other assets?.
Possible values:
  - 1: Yes
  - 8: DK

Column "ah04n_2" means: Value other assets.

Index(['ah03a', 'ah03b', 'ah03c', 'ah03d', 'ah03d1', 'ah03e', 'ah03f', 'ah03g',
       'ah03h', 'ah03i', 'ah03j', 'ah03k', 'ah03l', 'ah03m', 'ah03n',
       'ah04a_1', 'ah04a_2', 'ah04b_1', 'ah04b_2', 'ah04c_1', 'ah04c_2',
       'ah04d1_1', 'ah04d1_2', 'ah04d_1', 'ah04d_2', 'ah04e_1', 'ah04e_2',
       'ah04f_1', 'ah04f_2', 'ah04g_1', 'ah04g_2', 'ah04h_1', 'ah04h_2',
       'ah04i_1', 'ah04i_2', 'ah04j_1', 'ah04j_2', 'ah04k_1', 'ah04k_2',
       'ah04l_1', 'ah04l_2', 'ah04m_1', 'ah04m_2', 'ah04n_1', 'ah04n_2',
       'ah05a', 'ah05b', 'ah05g', 'ah05h', 'ah05i', 'ah05n', 'ah06a_1',
       'ah06a_2', 'ah06b_1', 'ah06b_2', 'ah06g_1', 'ah06g_2', 'ah06h_1',
       'ah06h_2', 'ah06i_1', 'ah06i_2', 'ah06n_1', 'ah06n_2', 'folio', 'ls'],
      dtype='object')

In [12]:
dataframes = {}
description_parts = []

for table_name in element:
    print(f"\nProcessing table: {table_name}")
    df = pd.read_stata(DATA_DIR / f"{table_name}.dta")

    dataframes[table_name] = df

    json_path = JSON_DIR / f"{table_name}_enriched.json"

    with open(json_path, "r", encoding="utf-8") as f:
        json_dict = json.load(f)

    text_description = variable_metadata_to_text(json_dict)

    description_parts.append(
        f"TABLE: {table_name}\n{text_description}"
    )

dataframe_description = "\n\n".join(description_parts)

prompt = build_query_plan_prompt(
    dataframes=dataframes,
    dataframe_description=dataframe_description,
    number_of_nested_queries=2,
    n_sample_rows=3
)

print(prompt)

Processing table: ii_portad
title json dict : {'edad': {'meaning': 'Age Interviewed'}, 'ent': {'meaning': 'State', 'values_label': {'Baja California': '2', 'Baja California Sur': '3', 'Campeche': '4', 'Coahuila': '5', 'Colima': '6', 'Chiapas': '7', 'Distrito Federal': '9', 'Durango': '10', 'Guanajuato': '11', 'Guerrero': '12', 'Hidalgo': '13', 'Jalisco': '14', 'Estado de México': '15', 'Michoacán': '16', 'Morelos': '17', 'Nayarit': '18', 'Nuevo León': '19', 'Oaxaca': '20', 'Puebla': '21', 'Querétaro': '22', 'Sinaloa': '25', 'Sonora': '26', 'Tamaulipas': '28', 'Tlaxcala': '29', 'Veracruz': '30', 'Yucatán': '31', 'Zacatecas': '32'}}, 'folio': {'meaning': 'Household ID'}, 'ls': {'meaning': 'Individual ID'}, 'rel': {'meaning': 'Result Interview'}}

Processing table: ii_inr
title json dict : {'folio': {'meaning': 'Household ID'}, 'inr02a': {'meaning': 'Last 12 months HHM produce/sell dairy food', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02b': {'meaning': 'Last 12 months HHM produce/sell canned goods', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02c': {'meaning': 'Last 12 months HHM produce/sell meat', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02d': {'meaning': 'Last 12 months HHM produce/sell egg', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02e': {'meaning': 'Last 12 months HHM produce/sell clothes', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02f': {'meaning': 'Last 12 months HHM produce/sell crafts', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02g': {'meaning': 'Last 12 months HHM produce/sell furniture', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02h': {'meaning': 'Last 12 months HHM produce/sell flowers/med plants', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02i': {'meaning': 'Last 12 months HHM produce/sell honey', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02j': {'meaning': 'Last 12 months HHM produce/sell fattening animals', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr02k': {'meaning': 'Last 12 months HHM produce/sell other', 'values_label': {'Yes': '1', 'No': '3'}}, 'inr03a': {'meaning': 'Last 12 months quantity sold: dairy products'}, 'inr03b': {'meaning': 'Last 12 months quantity sold: canned goods'}, 'inr03c': {'meaning': 'Last 12 months quantity sold: meat'}, 'inr03d': {'meaning': 'Last 12 months quantity sold: eggs'}, 'inr03e': {'meaning': 'Last 12 months quantity sold: clothes'}, 'inr03f': {'meaning': 'Last 12 months quantity sold: crafts'}, 'inr03g': {'meaning': 'Last 12 months quantity sold: furniture'}, 'inr03h': {'meaning': 'Last 12 months quantity sold: med plants'}, 'inr03i': {'meaning': 'Last 12 months quantity sold: honey'}, 'inr03j': {'meaning': 'Last 12 months quantity sold: fattening animals'}, 'inr03k': {'meaning': 'Last 12 months quantity sold: other'}, 'inr04a': {'meaning': 'Last month quantity sold: dairy products'}, 'inr04b': {'meaning': 'Last month quantity sold: canned goods'}, 'inr04c': {'meaning': 'Last month quantity sold: meat'}, 'inr04d': {'meaning': 'Last month quantity sold: eggs'}, 'inr04e': {'meaning': 'Last month quantity sold: clothes'}, 'inr04f': {'meaning': 'Last month quantity sold: crafts'}, 'inr04g': {'meaning': 'Last month quantity sold: furniture'}, 'inr04h': {'meaning': 'Last month quantity sold: med plants'}, 'inr04i': {'meaning': 'Last month quantity sold: honey'}, 'inr04j': {'meaning': 'Last month quantity sold: fattening animals'}, 'inr04k': {'meaning': 'Last month quantity sold: other'}, 'inr05a_1': {'meaning': 'HHM decide money selling: dairy food', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05b_1': {'meaning': 'HHM decide money selling: canned goods', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05c_1': {'meaning': 'HHM decide money selling: meat', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05d_1': {'meaning': 'HHM decide money selling: eggs', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05e_1': {'meaning': 'HHM decide money selling: clothes', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05f_1': {'meaning': 'HHM decide money selling: crafts', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05g_1': {'meaning': 'HHM decide money selling: furniture', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05h_1': {'meaning': 'HHM decide money selling: flower/med plants', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05i_1': {'meaning': 'HHM decide money selling: honey', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05j_1': {'meaning': 'HHM decide money selling: fattening animals', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'inr05k_1': {'meaning': 'HHM decide money selling: other', 'values_label': {'The respondent': '1', "The respondent's spouse": '2', "Respondent's son(s)/daughter(s)": '3', "The respondent's parents": '4', "The respondent's parents in law": '5', "Respondent's brother(s)/sister(s)": '6', "Respondent's brother(s)/sister(s) in law": '7', 'All the household members': '8', 'Others (specify)': '9'}}, 'ls': {'meaning': 'Individual ID Third Round'}}

Processing table: ii_crh
title json dict : {'folio': {'meaning': 'Household ID'}, 'crh01_1a': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Do not have savings': '1'}}, 'crh01_1b': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Bank': '2'}}, 'crh01_1c': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Cooperative': '3'}}, 'crh01_1d': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Savings, fund/cash': '4'}}, 'crh01_1e': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Batch': '5'}}, 'crh01_1f': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Withdrawn': '6'}}, 'crh01_1g': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Friend/Relative out of the household': '7'}}, 'crh01_1h': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Voluntary accounts in the Afores': '8'}}, 'crh01_1i': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Solidarity / Jointly cash': '9'}}, 'crh01_1j': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'At your household': '10'}}, 'crh01_1k': {'meaning': 'Which type of institution HHM have savings', 'values_label': {'Other (specify)': '11'}}, 'crh02_1': {'meaning': 'Last 12 months money owed credit/loans', 'values_label': {'Value': '1', 'Did not incur debts in the last 12 months': '2', 'DK': '8'}}, 'crh02_2': {'meaning': 'Last 12 months money value in pesos owed credit/loans'}, 'crh02a': {'meaning': 'More $500 / less $500?', 'values_label': {'Less than $500': '1', 'More than $500': '2'}}, 'crh02b': {'meaning': 'More $1000 / less $1000?', 'values_label': {'Less than $1,000': '1', 'More than $1,000': '2'}}, 'crh02c': {'meaning': 'More $5000 / less $5000?', 'values_label': {'Less than $5,000': '1', 'More than $5,000': '2'}}, 'crh02d': {'meaning': 'More $10000 / less $10000?', 'values_label': {'Less than $10,000': '1', 'More than $10,000': '2'}}, 'crh03_1': {'meaning': 'How much money has the household paid in the last 12 months', 'values_label': {'Value': '1', 'Did not pay anything in the last 12 months': '2', 'Do not have debts': '3', 'DK': '8'}}, 'crh03_2': {'meaning': 'Value money paid in pesos last 12 months'}, 'crh03a': {'meaning': 'More $500 / less $500?', 'values_label': {'Less than $500': '1', 'More than $500': '2'}}, 'crh03b': {'meaning': 'More $1000 / less $1000?', 'values_label': {'Less than $1,000': '1', 'More than $1,000': '2'}}, 'crh03c': {'meaning': 'More $5000 / less $5000?', 'values_label': {'Less than $5,000': '1', 'More than $5,000': '2'}}, 'crh03d': {'meaning': 'More $10000 / less $10000?', 'values_label': {'Less than $10,000': '1', 'More than $10,000': '2'}}, 'crh04_1': {'meaning': 'Total debts + interests', 'values_label': {'Value': '1', 'DK': '8'}}, 'crh04_2': {'meaning': 'Value pesos total debts + interests'}, 'crh04a': {'meaning': 'More $500 / less $500?', 'values_label': {'Less than $500': '1', 'More than $500': '2'}}, 'crh04b': {'meaning': 'More $1000 / less $1000?', 'values_label': {'Less than $1,000': '1', 'More than $1,000': '2'}}, 'crh04c': {'meaning': 'More $5000 / less $5000?', 'values_label': {'Less than $5,000': '1', 'More than $5,000': '2'}}, 'crh04d': {'meaning': 'More $10000 / less $10000?', 'values_label': {'Less than $10,000': '1', 'More than $10,000': '2'}}}
You are a query-planning assistant.

Your task is to generate a SQL-like query plan in JSON format.

The query plan will later be validated by a strict Pydantic schema and compiled into pandas code.

You are given:
1. A set of pandas DataFrames with their names, columns, dtypes, and sample rows.
2. A textual description explaining the semantic meaning of the DataFrames and their columns.
3. A required minimum number of nested query operations.

DATAFRAMES
==========

{
  "name": "ii_portad",
  "columns": [
    "edad",
    "ent",
    "folio",
    "ls",
    "rel"
  ],
  "dtypes": {
    "edad": "float32",
    "ent": "float32",
    "folio": "object",
    "ls": "object",
    "rel": "float32"
  },
  "sample_rows": [
    {
      "edad": 44.0,
      "ent": 20.0,
      "folio": "000010AP00",
      "ls": "02",
      "rel": 20.0
    },
    {
      "edad": 24.0,
      "ent": 20.0,
      "folio": "000010BP03",
      "ls": "01",
      "rel": 20.0
    },
    {
      "edad": 51.0,
      "ent": 20.0,
      "folio": "000020AP00",
      "ls": "02",
      "rel": 20.0
    }
  ]
}

{
  "name": "ii_inr",
  "columns": [
    "folio",
    "inr02a",
    "inr02b",
    "inr02c",
    "inr02d",
    "inr02e",
    "inr02f",
    "inr02g",
    "inr02h",
    "inr02i",
    "inr02j",
    "inr02k",
    "inr03a",
    "inr03b",
    "inr03c",
    "inr03d",
    "inr03e",
    "inr03f",
    "inr03g",
    "inr03h",
    "inr03i",
    "inr03j",
    "inr03k",
    "inr04a",
    "inr04b",
    "inr04c",
    "inr04d",
    "inr04e",
    "inr04f",
    "inr04g",
    "inr04h",
    "inr04i",
    "inr04j",
    "inr04k",
    "inr05a_1",
    "inr05b_1",
    "inr05c_1",
    "inr05d_1",
    "inr05e_1",
    "inr05f_1",
    "inr05g_1",
    "inr05h_1",
    "inr05i_1",
    "inr05j_1",
    "inr05k_1",
    "ls"
  ],
  "dtypes": {
    "folio": "object",
    "inr02a": "float32",
    "inr02b": "float32",
    "inr02c": "float32",
    "inr02d": "float32",
    "inr02e": "float32",
    "inr02f": "float32",
    "inr02g": "float32",
    "inr02h": "float32",
    "inr02i": "float32",
    "inr02j": "float32",
    "inr02k": "float32",
    "inr03a": "float32",
    "inr03b": "float32",
    "inr03c": "float32",
    "inr03d": "float32",
    "inr03e": "float32",
    "inr03f": "float32",
    "inr03g": "float32",
    "inr03h": "float32",
    "inr03i": "float32",
    "inr03j": "float32",
    "inr03k": "float32",
    "inr04a": "float32",
    "inr04b": "float32",
    "inr04c": "float32",
    "inr04d": "float32",
    "inr04e": "float32",
    "inr04f": "float32",
    "inr04g": "float32",
    "inr04h": "float32",
    "inr04i": "float32",
    "inr04j": "float32",
    "inr04k": "float32",
    "inr05a_1": "float32",
    "inr05b_1": "float32",
    "inr05c_1": "float32",
    "inr05d_1": "float32",
    "inr05e_1": "float32",
    "inr05f_1": "float32",
    "inr05g_1": "float32",
    "inr05h_1": "float32",
    "inr05i_1": "float32",
    "inr05j_1": "float32",
    "inr05k_1": "float32",
    "ls": "float32"
  },
  "sample_rows": [
    {
      "folio": "000010AP00",
      "inr02a": 3.0,
      "inr02b": 3.0,
      "inr02c": 3.0,
      "inr02d": 3.0,
      "inr02e": 3.0,
      "inr02f": 3.0,
      "inr02g": 3.0,
      "inr02h": 3.0,
      "inr02i": 3.0,
      "inr02j": 3.0,
      "inr02k": 3.0,
      "inr03a": NaN,
      "inr03b": NaN,
      "inr03c": NaN,
      "inr03d": NaN,
      "inr03e": NaN,
      "inr03f": NaN,
      "inr03g": NaN,
      "inr03h": NaN,
      "inr03i": NaN,
      "inr03j": NaN,
      "inr03k": NaN,
      "inr04a": NaN,
      "inr04b": NaN,
      "inr04c": NaN,
      "inr04d": NaN,
      "inr04e": NaN,
      "inr04f": NaN,
      "inr04g": NaN,
      "inr04h": NaN,
      "inr04i": NaN,
      "inr04j": NaN,
      "inr04k": NaN,
      "inr05a_1": NaN,
      "inr05b_1": NaN,
      "inr05c_1": NaN,
      "inr05d_1": NaN,
      "inr05e_1": NaN,
      "inr05f_1": NaN,
      "inr05g_1": NaN,
      "inr05h_1": NaN,
      "inr05i_1": NaN,
      "inr05j_1": NaN,
      "inr05k_1": NaN,
      "ls": 2.0
    },
    {
      "folio": "000010BP03",
      "inr02a": 3.0,
      "inr02b": 3.0,
      "inr02c": 3.0,
      "inr02d": 3.0,
      "inr02e": 3.0,
      "inr02f": 3.0,
      "inr02g": 3.0,
      "inr02h": 3.0,
      "inr02i": 3.0,
      "inr02j": 3.0,
      "inr02k": 3.0,
      "inr03a": NaN,
      "inr03b": NaN,
      "inr03c": NaN,
      "inr03d": NaN,
      "inr03e": NaN,
      "inr03f": NaN,
      "inr03g": NaN,
      "inr03h": NaN,
      "inr03i": NaN,
      "inr03j": NaN,
      "inr03k": NaN,
      "inr04a": NaN,
      "inr04b": NaN,
      "inr04c": NaN,
      "inr04d": NaN,
      "inr04e": NaN,
      "inr04f": NaN,
      "inr04g": NaN,
      "inr04h": NaN,
      "inr04i": NaN,
      "inr04j": NaN,
      "inr04k": NaN,
      "inr05a_1": NaN,
      "inr05b_1": NaN,
      "inr05c_1": NaN,
      "inr05d_1": NaN,
      "inr05e_1": NaN,
      "inr05f_1": NaN,
      "inr05g_1": NaN,
      "inr05h_1": NaN,
      "inr05i_1": NaN,
      "inr05j_1": NaN,
      "inr05k_1": NaN,
      "ls": 1.0
    },
    {
      "folio": "000020AP00",
      "inr02a": 3.0,
      "inr02b": 3.0,
      "inr02c": 3.0,
      "inr02d": 3.0,
      "inr02e": 3.0,
      "inr02f": 3.0,
      "inr02g": 3.0,
      "inr02h": 3.0,
      "inr02i": 3.0,
      "inr02j": 3.0,
      "inr02k": 3.0,
      "inr03a": NaN,
      "inr03b": NaN,
      "inr03c": NaN,
      "inr03d": NaN,
      "inr03e": NaN,
      "inr03f": NaN,
      "inr03g": NaN,
      "inr03h": NaN,
      "inr03i": NaN,
      "inr03j": NaN,
      "inr03k": NaN,
      "inr04a": NaN,
      "inr04b": NaN,
      "inr04c": NaN,
      "inr04d": NaN,
      "inr04e": NaN,
      "inr04f": NaN,
      "inr04g": NaN,
      "inr04h": NaN,
      "inr04i": NaN,
      "inr04j": NaN,
      "inr04k": NaN,
      "inr05a_1": NaN,
      "inr05b_1": NaN,
      "inr05c_1": NaN,
      "inr05d_1": NaN,
      "inr05e_1": NaN,
      "inr05f_1": NaN,
      "inr05g_1": NaN,
      "inr05h_1": NaN,
      "inr05i_1": NaN,
      "inr05j_1": NaN,
      "inr05k_1": NaN,
      "ls": 2.0
    }
  ]
}

{
  "name": "ii_crh",
  "columns": [
    "crh01_1a",
    "crh01_1b",
    "crh01_1c",
    "crh01_1d",
    "crh01_1e",
    "crh01_1f",
    "crh01_1g",
    "crh01_1h",
    "crh01_1i",
    "crh01_1j",
    "crh01_1k",
    "crh02_1",
    "crh02_2",
    "crh02a",
    "crh02b",
    "crh02c",
    "crh02d",
    "crh03_1",
    "crh03_2",
    "crh03a",
    "crh03b",
    "crh03c",
    "crh03d",
    "crh04_1",
    "crh04_2",
    "crh04a",
    "crh04b",
    "crh04c",
    "crh04d",
    "folio"
  ],
  "dtypes": {
    "crh01_1a": "float32",
    "crh01_1b": "float32",
    "crh01_1c": "float32",
    "crh01_1d": "float32",
    "crh01_1e": "float32",
    "crh01_1f": "float32",
    "crh01_1g": "float32",
    "crh01_1h": "float32",
    "crh01_1i": "float32",
    "crh01_1j": "float32",
    "crh01_1k": "float32",
    "crh02_1": "float32",
    "crh02_2": "float32",
    "crh02a": "float32",
    "crh02b": "float32",
    "crh02c": "float32",
    "crh02d": "float32",
    "crh03_1": "float32",
    "crh03_2": "float32",
    "crh03a": "float32",
    "crh03b": "float32",
    "crh03c": "float32",
    "crh03d": "float32",
    "crh04_1": "float32",
    "crh04_2": "float32",
    "crh04a": "float32",
    "crh04b": "float32",
    "crh04c": "float32",
    "crh04d": "float32",
    "folio": "object"
  },
  "sample_rows": [
    {
      "crh01_1a": 1.0,
      "crh01_1b": NaN,
      "crh01_1c": NaN,
      "crh01_1d": NaN,
      "crh01_1e": NaN,
      "crh01_1f": NaN,
      "crh01_1g": NaN,
      "crh01_1h": NaN,
      "crh01_1i": NaN,
      "crh01_1j": NaN,
      "crh01_1k": NaN,
      "crh02_1": 1.0,
      "crh02_2": 7000.0,
      "crh02a": NaN,
      "crh02b": NaN,
      "crh02c": NaN,
      "crh02d": NaN,
      "crh03_1": 1.0,
      "crh03_2": 7000.0,
      "crh03a": NaN,
      "crh03b": NaN,
      "crh03c": NaN,
      "crh03d": NaN,
      "crh04_1": 1.0,
      "crh04_2": 7000.0,
      "crh04a": NaN,
      "crh04b": NaN,
      "crh04c": NaN,
      "crh04d": NaN,
      "folio": "000010AP00"
    },
    {
      "crh01_1a": NaN,
      "crh01_1b": NaN,
      "crh01_1c": NaN,
      "crh01_1d": 4.0,
      "crh01_1e": NaN,
      "crh01_1f": NaN,
      "crh01_1g": NaN,
      "crh01_1h": NaN,
      "crh01_1i": NaN,
      "crh01_1j": NaN,
      "crh01_1k": NaN,
      "crh02_1": 2.0,
      "crh02_2": NaN,
      "crh02a": NaN,
      "crh02b": NaN,
      "crh02c": NaN,
      "crh02d": NaN,
      "crh03_1": 3.0,
      "crh03_2": NaN,
      "crh03a": NaN,
      "crh03b": NaN,
      "crh03c": NaN,
      "crh03d": NaN,
      "crh04_1": NaN,
      "crh04_2": NaN,
      "crh04a": NaN,
      "crh04b": NaN,
      "crh04c": NaN,
      "crh04d": NaN,
      "folio": "000010BP03"
    },
    {

In [13]:
from dotenv import load_dotenv
import os

load_dotenv()

API_KEY = os.getenv("API_KEY")

print(API_KEY[:10])  # optional check

sk-proj-c8

In [14]:
from openai import OpenAI

client = OpenAI(api_key=API_KEY)
response = client.chat.completions.create(
    model="gpt-5",
    messages=[
        {
            "role": "system",
            "content": (
                "You are a query-planning assistant. "
                "Return valid JSON only."
            )
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    response_format={"type": "json_object"}
)

In [15]:
import json

content = response.choices[0].message.content

output = json.loads(content)

print(output)

{'question': 'Among households that produced/sold at least one good in the last 12 months, which ones have the highest total debts + interests (crh04_2)?', 'query_plan': {'nodes': [{'id': 'n1', 'operation': 'scan', 'table': 'ii_inr'}, {'id': 'n2', 'operation': 'filter', 'input': 'n1', 'conditions': [{'column': 'inr02a', 'operator': '=', 'value': 3.0}, {'column': 'inr02b', 'operator': '=', 'value': 3.0}, {'column': 'inr02c', 'operator': '=', 'value': 3.0}, {'column': 'inr02d', 'operator': '=', 'value': 3.0}, {'column': 'inr02e', 'operator': '=', 'value': 3.0}, {'column': 'inr02f', 'operator': '=', 'value': 3.0}, {'column': 'inr02g', 'operator': '=', 'value': 3.0}, {'column': 'inr02h', 'operator': '=', 'value': 3.0}, {'column': 'inr02i', 'operator': '=', 'value': 3.0}, {'column': 'inr02j', 'operator': '=', 'value': 3.0}, {'column': 'inr02k', 'operator': '=', 'value': 3.0}]}, {'id': 'n3', 'operation': 'anti_join', 'left_input': 'n1', 'right_input': 'n2', 'left_on': 'folio', 'right_on': 'folio'}, {'id': 'n4', 'operation': 'scan', 'table': 'ii_crh'}, {'id': 'n5', 'operation': 'semi_join', 'left_input': 'n4', 'right_input': 'n3', 'left_on': 'folio', 'right_on': 'folio'}, {'id': 'n6', 'operation': 'filter', 'input': 'n5', 'conditions': [{'column': 'crh04_1', 'operator': '=', 'value': 1.0}, {'column': 'crh04_2', 'operator': '>', 'value': 0}]}, {'id': 'n7', 'operation': 'sort', 'input': 'n6', 'by': 'crh04_2', 'ascending': False}, {'id': 'n8', 'operation': 'limit', 'input': 'n7', 'n': 1}, {'id': 'n9', 'operation': 'scalar_filter', 'input': 'n6', 'column': 'crh04_2', 'operator': '=', 'scalar_input': 'n8', 'scalar_column': 'crh04_2'}, {'id': 'n10', 'operation': 'select', 'input': 'n9', 'columns': ['folio', 'crh04_2']}], 'output': 'n10'}}

In [16]:
from SQL_TYPE_ALONE import validate_query_plan, compile_query_plan

query_plan = output["query_plan"]

validated_plan = validate_query_plan(query_plan)

print(validated_plan)

ValidationError: 28 validation errors for QueryPlan
nodes.8.ScanNode.operation
  Input should be 'scan' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.ScanNode.table
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.FilterNode.operation
  Input should be 'filter' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.FilterNode.conditions
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.SelectNode.operation
  Input should be 'select' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.SelectNode.columns
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.JoinNode.operation
  Input should be 'join' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.JoinNode.left_input
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.JoinNode.right_input
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.JoinNode.left_on
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.JoinNode.right_on
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.GroupByNode.operation
  Input should be 'groupby' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.GroupByNode.by
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.GroupByNode.aggregations
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.SortNode.operation
  Input should be 'sort' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.SortNode.by
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.LimitNode.operation
  Input should be 'limit' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.LimitNode.n
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.SemiJoinNode.operation
  Input should be 'semi_join' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.SemiJoinNode.left_input
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.SemiJoinNode.right_input
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.SemiJoinNode.left_on
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.SemiJoinNode.right_on
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.AntiJoinNode.operation
  Input should be 'anti_join' [type=literal_error, input_value='scalar_filter', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error
nodes.8.AntiJoinNode.left_input
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.AntiJoinNode.right_input
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.AntiJoinNode.left_on
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
nodes.8.AntiJoinNode.right_on
  Field required [type=missing, input_value={'id': 'n9', 'operation':...alar_column': 'crh04_2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing

In [17]:
from openai import OpenAI
from SQL_TYPE_ALONE import validate_or_repair_query_plan, compile_query_plan

### ONLY IF PYDANTIC ERRORS

In [18]:

client = OpenAI(api_key=API_KEY)

query_plan = output["query_plan"]

result = validate_or_repair_query_plan(
    query_plan=query_plan,
    client=client,
    model="gpt-5",
    max_repair_attempts=2,
)

validated_plan = result["validated_plan"]
repaired_query_plan = result["repaired_query_plan"]

print("Was repaired:", result["was_repaired"])
print("Repair attempts:", result["repair_attempts"])

print(repaired_query_plan)

Was repaired: True
Repair attempts: 1
{'nodes': [{'id': 'n1', 'operation': 'scan', 'table': 'ii_inr'}, {'id': 'n2', 'operation': 'filter', 'input': 'n1', 'conditions': [{'column': 'inr02a', 'operator': '=', 'value': 3.0}, {'column': 'inr02b', 'operator': '=', 'value': 3.0}, {'column': 'inr02c', 'operator': '=', 'value': 3.0}, {'column': 'inr02d', 'operator': '=', 'value': 3.0}, {'column': 'inr02e', 'operator': '=', 'value': 3.0}, {'column': 'inr02f', 'operator': '=', 'value': 3.0}, {'column': 'inr02g', 'operator': '=', 'value': 3.0}, {'column': 'inr02h', 'operator': '=', 'value': 3.0}, {'column': 'inr02i', 'operator': '=', 'value': 3.0}, {'column': 'inr02j', 'operator': '=', 'value': 3.0}, {'column': 'inr02k', 'operator': '=', 'value': 3.0}]}, {'id': 'n3', 'operation': 'anti_join', 'left_input': 'n1', 'right_input': 'n2', 'left_on': 'folio', 'right_on': 'folio'}, {'id': 'n4', 'operation': 'scan', 'table': 'ii_crh'}, {'id': 'n5', 'operation': 'semi_join', 'left_input': 'n4', 'right_input': 'n3', 'left_on': 'folio', 'right_on': 'folio'}, {'id': 'n6', 'operation': 'filter', 'input': 'n5', 'conditions': [{'column': 'crh04_1', 'operator': '=', 'value': 1.0}, {'column': 'crh04_2', 'operator': '>', 'value': 0}]}, {'id': 'n7', 'operation': 'sort', 'input': 'n6', 'by': 'crh04_2', 'ascending': False}, {'id': 'n8', 'operation': 'limit', 'input': 'n7', 'n': 1}, {'id': 'n9', 'operation': 'semi_join', 'left_input': 'n6', 'right_input': 'n8', 'left_on': 'crh04_2', 'right_on': 'crh04_2'}, {'id': 'n10', 'operation': 'select', 'input': 'n9', 'columns': ['folio', 'crh04_2']}], 'output': 'n10'}

### FROM JSON TO CODE

In [19]:
from SQL_TYPE_ALONE import compile_query_plan, validate_query_plan

In [20]:
code = compile_query_plan(validated_plan)
print(code)

import pandas as pd

def run_query(tables: dict[str, pd.DataFrame]) -> pd.DataFrame:
    n1 = tables['ii_inr'].copy()
    n2 = n1[(n1['inr02a'] == 3.0) & (n1['inr02b'] == 3.0) & (n1['inr02c'] == 3.0) & (n1['inr02d'] == 3.0) & (n1['inr02e'] == 3.0) & (n1['inr02f'] == 3.0) & (n1['inr02g'] == 3.0) & (n1['inr02h'] == 3.0) & (n1['inr02i'] == 3.0) & (n1['inr02j'] == 3.0) & (n1['inr02k'] == 3.0)].copy()
    n3 = n1[~n1['folio'].isin(n2['folio'])].copy()
    n4 = tables['ii_crh'].copy()
    n5 = n4[n4['folio'].isin(n3['folio'])].copy()
    n6 = n5[(n5['crh04_1'] == 1.0) & (n5['crh04_2'] > 0)].copy()
    n7 = n6.sort_values('crh04_2', ascending=False)
    n8 = n7.head(1)
    n9 = n6[n6['crh04_2'].isin(n8['crh04_2'])].copy()
    n10 = n9[['folio', 'crh04_2']].copy()

    return n10

In [21]:
def get_required_tables(plan_json: dict) -> set[str]:
    plan = validate_query_plan(plan_json)

    required_tables = set()

    for node in plan.nodes:
        if node.operation == "scan":
            required_tables.add(node.table)

    return required_tables


def execute_query_plan(plan_json: dict, tables: dict):
    required_tables = get_required_tables(plan_json)

    missing_tables = required_tables - set(tables.keys())

    if missing_tables:
        raise ValueError(
            f"Missing required table(s): {sorted(missing_tables)}. "
            f"Available tables: {sorted(tables.keys())}"
        )

    code = compile_query_plan(plan_json)

    namespace = {}

    exec(code, namespace)

    run_query = namespace["run_query"]

    return run_query(tables)

In [22]:
plan_dict = validated_plan.model_dump()

print(get_required_tables(plan_dict))

{'ii_crh', 'ii_inr'}

In [25]:
tables = {
    "ii_portad": df_ii_portad_cover_book,
    "ii_su": df_ii_su_land_household,
    "ii_su1": df_ii_su1_land_household_details,
    "ii_inr": df_ii_inr_rural_income,
    "ii_nna": df_ii_nna_non_agricultural_business,
    "ii_nna1": df_ii_nna1_non_agricultural_business_details,
    "ii_ah": df_ii_ah_household_assets,
    "ii_crh": df_ii_crh_household_credit,
    "ii_in": df_ii_in_household_non_labor_income,
    "ii_se": df_ii_se_household_economic_shocks,
    "ii_vlh": df_ii_vlh_household_crime_victimization,
    "ii_vlh1": df_ii_vlh1_household_crime_victimization_details,
    "ii_ne": df_ii_ne_interview_session_notes,
    "ii_conpor": df_ii_conpor_visits_control,
}

In [26]:
result = execute_query_plan(plan_dict, tables)

result

           folio   crh04_2
3590  041820AP00  440000.0

In [27]:
from openai import OpenAI
from SQL_TYPE_ALONE import query_plan_to_question

In [28]:
client = OpenAI(api_key=API_KEY)

question = query_plan_to_question(
    query_plan=validated_plan.model_dump(),
    client=client,
    model="gpt-5",
    dataframe_description=dataframe_description,
)

print(question)

Among households that reported producing or selling any of dairy, canned goods, meat, eggs, clothes, crafts, furniture, flowers/medicinal plants, honey, fattening animals, or other goods in the last 12 months, which household(s) has the highest recorded positive total debts plus interests, and what is that amount?

In [29]:
import json
from pathlib import Path

ROOT = Path.cwd()
JSON_DIR = ROOT / "data" / "hh09dta_b2" / "codebook_json"


def variable_metadata_to_text(json_dict: dict) -> str:
    lines = []

    for column_name, metadata in json_dict.items():
        meaning = metadata.get("meaning", "No meaning provided")
        values_label = metadata.get("values_label")

        lines.append(f'Column "{column_name}" means: {meaning}.')

        if values_label:
            lines.append("Possible values:")
            for label, value in values_label.items():
                lines.append(f"  - {value}: {label}")

        lines.append("")

    return "\n".join(lines)


for json_path in JSON_DIR.glob("*_enriched.json"):
    txt_path = json_path.with_suffix(".txt")

    with open(json_path, "r", encoding="utf-8") as f:
        json_dict = json.load(f)

    text = variable_metadata_to_text(json_dict)

    txt_path.write_text(text, encoding="utf-8")

    print(f"Created: {txt_path.name}")

Created: ii_inr_enriched.txt
Created: ii_ah_enriched.txt
Created: ii_vlh_enriched.txt
Created: ii_su_enriched.txt
Created: ii_vlh1_enriched.txt
Created: ii_nna1_enriched.txt
Created: ii_ne_enriched.txt
Created: ii_portad_enriched.txt
Created: ii_conpor_enriched.txt
Created: ii_su1_enriched.txt
Created: ii_se_enriched.txt
Created: ii_crh_enriched.txt
Created: ii_nna_enriched.txt
Created: ii_in_enriched.txt

In [32]:
import pandas as pd
from pathlib import Path

CSV_PATH = Path("data/dataset_query.csv")

df = pd.read_csv(CSV_PATH)

print("Columns:")
print(df.columns.tolist())

print("\nFirst rows:")
print(df.head(15))

print("\nShape:")
print(df.shape)

Columns:
['question_from_llm', 'natural_question_arisen_from_code', 'python_script_path', 'tables', 'text', 'source_dataset', 'check_if_code_works', 'error_message']

First rows:
                                    question_from_llm  \
0   In Oaxaca (state code 20), among households wh...
1   Which state(s) have the highest total value of...
2   In Oaxaca (ent=20), which 5 households have to...
3   Among interviewed individuals in Oaxaca (state...
4   Among households that received income from an ...
5   By state, among individuals living in househol...
6   Among individuals in Oaxaca (ent=20) who live ...
7   Which states have an average age of interviewe...
8   Which Mexican state(s) have the highest number...
9   Which 5 states have the highest number of inte...
10  Among adults (18+) in Oaxaca who live in house...
11  Among adults (age >= 18) interviewed, which st...
12  Among households in Oaxaca (ent=20) that have ...

                    natural_question_arisen_from_code  \
0   In Oaxaca, among households with at least one ...
1   Among households that received any direct inco...
2   Among households in Oaxaca that received a pos...
3   Among individuals in Oaxaca living in househol...
4   Among households that reported receiving incom...
5   By state, what is the average interviewed age ...
6   Among households in Oaxaca that own an electro...
7   Among households that reported receiving Licon...
8   Which state(s) have the most households that b...
9   Which five states have the most individuals li...
10  Among individuals aged 18 or older in Oaxaca w...
11  Among adults (18+) living in households that p...
12  Which 10 households in Oaxaca (by Household ID...

                                   python_script_path  \
0   data/python_script_for_queries/hh09dta_b2/SQL_...
1   data/python_script_for_queries/hh09dta_b2/SQL_...
2   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
3   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
4   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
5   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
6   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
7   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
8   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
9   python_script_for_queries/hh09dta_b2/SQL_TYPE_...
10  python_script_for_queries/hh09dta_b2/SQL_TYPE_...
11  python_script_for_queries/hh09dta_b2/SQL_TYPE_...
12  python_script_for_queries/hh09dta_b2/SQL_TYPE_...

                               tables  \
0     ["ii_portad", "ii_in", "ii_ah"]
1     ["ii_portad", "ii_ah", "ii_in"]
2    ["ii_portad", "ii_in", "ii_crh"]
3   ["ii_portad", "ii_nna", "ii_inr"]
4     ["ii_portad", "ii_in", "ii_ah"]
5    ["ii_portad", "ii_su", "ii_inr"]
6     ["ii_portad", "ii_ah", "ii_in"]
7    ["ii_portad", "ii_in", "ii_inr"]
8    ["ii_portad", "ii_inr", "ii_su"]
9   ["ii_portad", "ii_inr", "ii_nna"]
10   ["ii_portad", "ii_nna", "ii_ah"]
11  ["ii_portad", "ii_crh", "ii_inr"]
12   ["ii_portad", "ii_in", "ii_inr"]

                                                 text source_dataset  \
0   ["ii_portad_enriched.txt", "ii_in_enriched.txt...     hh09dta_b2
1   ["ii_portad_enriched.txt", "ii_ah_enriched.txt...     hh09dta_b2
2   ["ii_portad_enriched.txt", "ii_in_enriched.txt...     hh09dta_b2
3   ["ii_portad_enriched.txt", "ii_nna_enriched.tx...     hh09dta_b2
4   ["ii_portad_enriched.txt", "ii_in_enriched.txt...     hh09dta_b2
5   ["ii_portad_enriched.txt", "ii_su_enriched.txt...     hh09dta_b2
6   ["ii_portad_enriched.txt", "ii_ah_enriched.txt...     hh09dta_b2
7   ["ii_portad_enriched.txt", "ii_in_enriched.txt...     hh09dta_b2
8   ["ii_portad_enriched.txt", "ii_inr_enriched.tx...     hh09dta_b2
9   ["ii_portad_enriched.txt", "ii_inr_enriched.tx...     hh09dta_b2
10  ["ii_portad_enriched.txt", "ii_nna_enriched.tx...     hh09dta_b2
11  ["ii_portad_enriched.txt", "ii_crh_enriched.tx...     hh09dta_b2
12  ["ii_portad_enriched.txt", "ii_in_enriched.txt...     hh09dta_b2

   check_if_code_works  error_message
0                   no            NaN
1                   no            NaN
2                   no            NaN
3                   no            NaN
4                   no            NaN
5                   no            NaN
6                   no            NaN
7                   no            NaN
8                   no            NaN
9                   no            NaN
10                  no            NaN
11                  no            NaN
12                  no            NaN

Shape:
(13, 8)

In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("data/hh09dta_b2")

results = []

for dta_file in sorted(DATA_DIR.glob("*.dta")):
    try:
        df = pd.read_stata(dta_file)

        results.append(
            {
                "table": dta_file.stem,
                "n_rows": len(df),
                "n_columns": len(df.columns),
            }
        )

    except Exception as e:
        results.append(
            {
                "table": dta_file.stem,
                "n_rows": None,
                "n_columns": None,
            }
        )

summary_df = pd.DataFrame(results)

summary_df = summary_df.sort_values(
    by="n_rows",
    ascending=False,
)

summary_df

        table  n_rows  n_columns
1   ii_conpor    9487         14
0       ii_ah    9092         65
2      ii_crh    9092         30
3       ii_in    9092         65
4      ii_inr    9092         46
5       ii_ne    9092          9
6      ii_nna    9092          3
8   ii_portad    9092          5
9       ii_se    9092         64
10      ii_su    9092         26
12     ii_vlh    9092         64
11     ii_su1    1985         60
7     ii_nna1    1090         80
13    ii_vlh1     600         43

In [1]:
import pandas as pd

df = pd.read_csv("data/dataset_query.csv")

print(df.columns.tolist())
print(df.shape)

for col in df.columns:
    print(col)

['question_from_llm', 'natural_question_arisen_from_code', 'python_script_path', 'tables', 'text', 'source_dataset', 'check_if_code_works']
(23, 7)
question_from_llm
natural_question_arisen_from_code
python_script_path
tables
text
source_dataset
check_if_code_works

In [4]:
### show the the questions from the dataset_query.csv, the column natural_question_arisen_from_code
questions = df["natural_question_arisen_from_code"].tolist()

for question in questions:
    print(question)

Which 10 states have the highest average age of interviewed individuals living in households that reported feeling unsafe or very unsafe at home and that received a positive amount directly from an Other Government Program, and how many individuals are included per state?
Among households that reported a household member died in the last five years, what is the average number of non-agricultural businesses owned or shared in the last 12 months in each state, and how many such households are there per state, ranked from highest to lowest average?
Among households that use a plot/land for farming and have produced or sold meat in the last 12 months, which 10 states have the highest average age of interviewed individuals, and how many such individuals are in each state?
Which five households (by ID) in Oaxaca that reported a household member’s disease/accident/hospitalization in the last five years and produced/sold eggs in the last 12 months have the highest average member age, and what are their average ages and numbers of individuals?
Among individuals living in households that both reported losing their home or business to a natural disaster in the last five years and use a plot of land for farming, what is the average age and the number of individuals in each state, ordered by highest average age?
What are the top 10 states with the highest average amount received directly from Other Government Program in the last 12 months among households that both received Liconsa milk and use land for farming, and how many such households are in each state?
Which five states have the highest average number of times households have been entered or robbed (house, business, or parcel) since 2005, among households that received Liconsa milk in the last 12 months and include at least one person aged 50 or older, and how many such households are in each state?
Among interviewed individuals living in households that own or share a non‑agricultural business, what is the average age and the number of individuals for each 'Feel safe at home?' response category, sorted from highest to lowest average age?
By state, what is the average age of interviewed individuals and the number of individuals in households that use a plot of land for farming and reported a total crop loss in the last five years, ranked by highest average age?
Among households in Oaxaca (State=20) with at least one member who owns/shares a non‑agricultural business, which 10 Household IDs have the highest reported total debts plus interest (in pesos), and what is each household’s size?
For each state, how many individuals live in households that produced/sold dairy products in the last 12 months but did not use a plot/land for sowing or farming, and what is their average age, ranked by number of individuals (highest first)?
Among households that reported receiving Liconsa Milk in the last 12 months and produced/sold dairy foods in the last 12 months, which 10 households received the highest direct amounts from the Other Government Program, and what is the average age of interviewed persons in each?
Which 10 states have the highest average age of interviewed individuals living in households that reported a parcel being forcibly robbed since 2005, and for each of those states, what are the corresponding average ages and respondent counts for households that did (Yes) and did not (No) report such robberies?
Among households that use a plot/land for sowing/farming/vegetables and received a positive direct amount from Other Government Program in the last 12 months, which 10 states have the highest average household age, and how many such households are in each state?
By state, how many individuals live in households that use a plot or land for cultivation, reported a household member's death in the last five years, and took some coping action (excluding those that did nothing), ranked from highest to lowest?
Among households that own an electronic device and reported losing their dwelling or business to a natural disaster in the last five years, what is the average age of interviewed individuals by state, and how many individuals are in each state, ordered by highest average age?
By state, what is the average age of interviewed individuals living in households that reported feeling unsafe or very unsafe at home, and how many such individuals were interviewed in each state, ordered from highest to lowest average age?
Which state has the highest average amount received directly from the Other Government Program among households that received a positive amount, and how many recipient households are in that state?
Among households that both use a plot/land for farming (su01=1) and own/share a non‑agricultural business (nna01=1), which 10 states have the highest average age of interviewed individuals, and how many individuals are included per state?
Which state(s) has the highest average age, and what is that average, among interviewed individuals living in households that reported feeling unsafe or very unsafe at home and that produced/sold crafts in the last 12 months?
Among households that use a plot/land for farming and also own or share a non-agricultural business, and where the individual with ID 01 is age 30 or older, which five states have the highest average household spending on seeds?
By state, how many households both use a plot/land for sowing, farming, or vegetables and have at least one member who owns or shares a non‑agricultural business, ranked from highest to lowest?
Which state or states have the highest number of adults (age 18+) living in households that both use a plot/land for farming and own or share a non-agricultural business, and what is that count?

In [7]:
import pandas as pd

CSV_PATH = "data/dataset_query.csv"

df = pd.read_csv(CSV_PATH)

df.loc[
    df["python_script_path"]
    ==
    "python_script_for_queries/SQL_TYPE_ALONE/hh09dta_b2/query_000024.py",
    "python_script_path",
] = (
    "data/python_script_for_queries/"
    "SQL_TYPE_ALONE/"
    "hh09dta_b2/"
    "query_000024.py"
)

df.to_csv(
    CSV_PATH,
    index=False,
)

print(
    df[
        df["python_script_path"]
        .str.contains(
            "query_000024",
            na=False,
        )
    ][["python_script_path"]]
)

                                   python_script_path
23  data/python_script_for_queries/hh09dta_b2/SQL_...

In [8]:
import pandas as pd

CSV_PATH = "data/dataset_query.csv"

df = pd.read_csv(CSV_PATH)

mask = df["python_script_path"].str.contains("query_000024", na=False)

df.loc[mask, "python_script_path"] = (
    "python_script_for_queries/"
    "hh09dta_b2/"
    "SQL_TYPE_ALONE/"
    "query_000024.py"
)

df.to_csv(CSV_PATH, index=False)

print(df.loc[mask, ["python_script_path"]])

                                   python_script_path
23  python_script_for_queries/hh09dta_b2/SQL_TYPE_...

In [1]:
import pandas as pd
from pathlib import Path

CSV_PATH = "data/dataset_query.csv"

df = pd.read_csv(CSV_PATH)

def normalize_path(path):
    filename = Path(path).name

    return (
        "python_script_for_queries/"
        "SQL_TYPE_ALONE/"
        "hh09dta_b2/"
        f"{filename}"
    )

df["python_script_path"] = (
    df["python_script_path"]
    .apply(normalize_path)
)

df.to_csv(
    CSV_PATH,
    index=False,
)

print(df["python_script_path"].head(30))

0     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
1     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
2     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
3     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
4     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
5     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
6     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
7     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
8     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
9     python_script_for_queries/SQL_TYPE_ALONE/hh09d...
10    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
11    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
12    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
13    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
14    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
15    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
16    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
17    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
18    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
19    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
20    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
21    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
22    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
23    python_script_for_queries/SQL_TYPE_ALONE/hh09d...
Name: python_script_path, dtype: object